name: nf-ncov-voc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - biopython=1.78
  - pandas=1.2.4
  - bwa=0.7.17
  - samtools=1.12
  - bcftools=1.12
  - ivar=1.3.1
  - csvtk=0.23
  - graphviz=2.47.1
  - bbmap=38.90
  - seqtk=1.3
  - htslib=1.12
  - minimap2=2.18
  - freebayes=1.3.5
  - pysam=0.16.0
  - seqkit=0.16.0
